const fs = require('fs');
const path = require('path');
const config = require('../docmd.config.json');

const siteDir = path.join(__dirname, '../site');
const defaultLocale = config.i18n.default;
const locales = config.i18n.locales.map(l => l.id);
const nonDefaultLocales = locales.filter(id => id !== defaultLocale);

/**
 * Strip the auto-injected docmd client-side i18n runtime.
 *
 * In stringMode, translations are already baked into the HTML at build time.
 * The client-side script conflicts by re-applying translations (and worse,
 * uses localStorage to bleed locale preferences across pages — e.g. visiting
 * /zh/ then going back to / would show Chinese on the English page).
 *
 * We remove:
 *   1. <script>window.DOCMD_I18N = {...};</script>  (inline config)
 *   2. <script src="./assets/js/docmd-i18n-strings.js?v=..."></script>  (runtime)
 */
function stripI18nClientScript(html) {
    // Remove inline DOCMD_I18N config
    html = html.replace(/<script>window\.DOCMD_I18N\s*=\s*\{[^<]*\};\s*<\/script>\s*/g, '');
    // Remove the runtime script tag (handles relative paths and cache-bust query strings)
    html = html.replace(/<script\s+src="[^"]*docmd-i18n-strings\.js[^"]*">\s*<\/script>\s*/g, '');
    return html;
}

/**
 * Rewrite docs.docmd.io links to include the locale prefix.
 * e.g. href="https://docs.docmd.io/getting-started/installation"
 *   → href="https://docs.docmd.io/zh/getting-started/installation"
 */
function rewriteDocsLinks(html, locale) {
    return html.replace(/href="https:\/\/docs\.docmd\.io([^"]*)"/g, (match, pathname) => {
        // Already has locale prefix
        if (pathname.startsWith(`/${locale}/`) || pathname === `/${locale}`) {
            return match;
        }
        const cleanPath = pathname === '' || pathname === '/' ? '' : pathname;
        return `href="https://docs.docmd.io/${locale}${cleanPath}"`;
    });
}

/**
 * Rewrite local site links to keep navigation localized on non-default locale pages.
 * e.g. href="/search/" -> href="/zh/search/"
 *      href="/" -> href="/zh/"
 */
function rewriteLocalLinks(html, locale) {
    if (locale === 'en') return html;
    return html
        .replace(/href="\/search\/" class="nav-link"/g, `href="/${locale}/search/" class="nav-link"`)
        .replace(/href="\/" class="nav-logo"/g, `href="/${locale}/" class="nav-logo"`);
}

/**
 * Ensure language switcher links use root-absolute paths (e.g. href="/ru/" instead of href="./ru/").
 * In subdirectories like /de/, relative paths like ./ru/ resolve incorrectly to /de/ru/.
 */
function fixLangSwitcherLinks(html) {
    return html.replace(/<a class="lang-option\b([^"]*)" href="[^"]*" data-lang="([^"]+)"/g, (match, classes, lang) => {
        const targetHref = lang === defaultLocale ? '/' : `/${lang}/`;
        return `<a class="lang-option${classes}" href="${targetHref}" data-lang="${lang}"`;
    });
}

// --- Helper to recursively find all HTML files ---
function getAllHtmlFiles(dir) {
    let results = [];
    if (!fs.existsSync(dir)) return results;
    const list = fs.readdirSync(dir);
    list.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat && stat.isDirectory()) {
            results = results.concat(getAllHtmlFiles(filePath));
        } else if (file.endsWith('.html')) {
            results.push(filePath);
        }
    });
    return results;
}

// Cache for loaded translation JSONs
const translationsCache = {};
function getTranslations(locale) {
    if (!translationsCache[locale]) {
        const jsonPath = path.join(__dirname, `../assets/i18n/${locale}.json`);
        if (fs.existsSync(jsonPath)) {
            translationsCache[locale] = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        } else {
            translationsCache[locale] = {};
        }
    }
    return translationsCache[locale];
}

/**
 * Cleanly apply translations to all data-i18n and data-i18n-html elements,
 * completely replacing any duplicated or concatenated text generated by docmd build.
 */
function cleanI18nTranslations(html, locale) {
    const dict = getTranslations(locale);
    if (!dict || Object.keys(dict).length === 0) return html;

    const regex = /<([a-z0-9]+)\b([^>]*?\bdata-i18n(-html)?=["\x27]([^"\x27]+)["\x27][^>]*)>([\s\S]*?)<\/\1>/gi;

    const replaceFn = (fullMatch, tagName, attrString, isHtml, key, innerContent) => {
        if (key in dict) {
            const val = dict[key];
            return `<${tagName}${attrString}>${val}</${tagName}>`;
        }
        return fullMatch;
    };

    // Run 2 passes to ensure sibling/nested data-i18n tags are cleanly resolved
    let result = html.replace(regex, replaceFn);
    result = result.replace(regex, replaceFn);
    return result;
}

// --- Process all HTML files recursively ---
const htmlFiles = getAllHtmlFiles(siteDir);
htmlFiles.forEach(filePath => {
    const relativePath = path.relative(siteDir, filePath);
    const firstSegment = relativePath.split(path.sep)[0];
    const isLocale = nonDefaultLocales.includes(firstSegment);
    const fileLocale = isLocale ? firstSegment : defaultLocale;

    let html = fs.readFileSync(filePath, 'utf-8');
    html = stripI18nClientScript(html);
    html = cleanI18nTranslations(html, fileLocale);
    html = fixLangSwitcherLinks(html);
    if (isLocale) {
        html = rewriteDocsLinks(html, fileLocale);
        html = rewriteLocalLinks(html, fileLocale);
    }
    fs.writeFileSync(filePath, html, 'utf-8');
    console.log(`[rewrite-links] ${relativePath} → stripped i18n client runtime, applied clean i18n for locale: ${fileLocale}`);
});

// --- Clean up the runtime file itself (optional, saves bytes) ---
const runtimeFile = path.join(siteDir, 'assets/js/docmd-i18n-strings.js');
if (fs.existsSync(runtimeFile)) {
    fs.unlinkSync(runtimeFile);
    console.log(`[rewrite-links] Deleted orphaned assets/js/docmd-i18n-strings.js`);
}